services:
  nginx:
    build:
      context: .
      dockerfile: packages/api-gateway/Dockerfile
      target: ${BUILD_TARGET:-production}
    ports:
      - '${NGINX_PORT:-8080}:80' # Only expose nginx port
    volumes:
      - ./packages/api-gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./packages/api-gateway/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      client_app:
        condition: service_started
    restart: unless-stopped

  client_app:
    build:
      context: .
      dockerfile: packages/client/Dockerfile
      target: ${BUILD_TARGET:-production}
    expose:
      - '4200' # Only expose to internal docker network
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '4200']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped
