version: '3.8'

services:
  nginx:
    build:
      context: ./packages/api-gateway # Path to the api-gateway service
      dockerfile: Dockerfile
    ports:
      - '80:80' # Map port 80 on the host to port 80 in the container
    volumes:
      - ./packages/api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf
  client_app:
    build:
      context: ./packages/client # Path to the client service
      dockerfile: Dockerfile
    ports:
      - '80:80' # Map port 80 on the host to port 80 in the container
    volumes:
      - ./packages/client/nginx.conf:/etc/nginx/conf.d/default.conf
